name: public action testing for file changes 
on: 
  workflow_dispatch:
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
