name: variable test
on: 
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - env:
          VARIABLE: ${{ vars.MY_VARIABLE }}
        run: |
          echo "VARIABLE=$VARIABLE"
          if [[ "$VARIABLE" != 'hello world' ]]; then
            echo 'Unexpected variable value'
            exit 1
          fi
